name: Check Artifact Actions Version

on:
  schedule:
    - cron: '0 0 * * 1' # Executa toda segunda-feira às 00:00

jobs:
  check_versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Check workflows
        run: node check-versions.js
